# Generated by Django 3.2 on 2022-07-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concurs',
            options={'ordering': ['-id'], 'verbose_name': 'Фестиваль', 'verbose_name_plural': 'Фестивали'},
        ),
    ]
